package filesystem

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Time is an autogenerated mock type for the Time type
type MockTime struct {
	mock.Mock
}

// Now provides a mock function with given fields:
func (_m *MockTime) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}
